packages:
  - apps/*
  - packages/*

# 依赖版本号
catalog:
  amis: ^6.13.0
  amis-ui: ^6.13.0
  amis-core: ^6.13.0
  amis-editor-core: ^6.13.0
  amis-editor: ^6.13.0
  i18n-runtime: 1.0.10
  axios: ^1.12.2
  copy-to-clipboard: ^3.3.3
  mobx: ^4.5.0
  mobx-react: ^6.3.1
  mobx-state-tree: ^3.17.3
  react: ^18.2.0
  react-dom: ^18.2.0
  react-router-dom: ^6.18.0
  "@fortawesome/fontawesome-free": ^7.1.0
  #开发依赖
  vite: ^6.3.6
  "@eslint/js": ^9.36.0
  "@types/node": ^24.6.0
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
  "@vitejs/plugin-react": ^4.7.0
  eslint: ^9.36.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.22
  globals: ^16.4.0
  typescript: ~5.9.3
  typescript-eslint: ^8.45.0